site_name: PyData Conference Notes

nav:
  - Home: index.md
  - sktime talk: 01_sktime.md
  - polars: 02_polars.md
  - python best practises: 03_best_practises.md
  - Spark an Delta Lakes: 04_delta_lake.md
  - LLMs: 05_large_language_models.md
  - ML Platforms:  06_ml_platforms.md
  - PyData Executives: 07_pydata_for_executives.md
  - Fast API: 08_fast_ape.md
  - Pandas 2: 09_pandas_polar.md
  - Dask: 10_new_dev_pandas_and_dask.md
  - Correlation: 11_correlation_to_causation.md
  - Taipy: 12_taipy_for_web_app_data_science.md
